<a href="https://colab.research.google.com/github/big91987/kaikeba_kaggle/blob/master/homework_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1.使用梯度下降求解
$\mathrm{L}=\left(\theta_{1}-3\right)^{2}+\left(2 \theta_{2}-5\right)^{2}$的最小值点

In [0]:
theta1 , theta2 = 0.0,0.0
alpha = 0.1
for i in range(100):
    theta1 = theta1 - alpha*2*(theta1-3)
    theta2 = theta2 - alpha*2*(2*theta2 -5)*2
    print(theta1,theta2)

2. 使用梯度下降求解
$\mathrm{L}=\left(\theta_{1}-3\right)^{2}\left(2 \theta_{2}-5\right)^{2}$的最小值点

In [0]:
theta1 , theta2 = 10.0,4.0
alpha = 0.01
for i in range(100):
    theta1 = theta1 - alpha*2*(theta1-3)*(2*theta2-5)*(2*theta2-5)
    theta2 = theta2 - alpha*2*(2*theta2 -5)*2*(theta1-3)*(theta1-3)
    print(theta1,theta2)

3. 使用梯度下降实现最小二乘法

In [0]:
import numpy as np
import pandas as pd

In [0]:
def LinearRegression(X,y,alpha,n_rounds):
    n_features = X.shape[1]
    beta = np.array([0.0]*n_features)
    for i in range(n_rounds):
        
        #计算 epsilon
        epsilon = y
        for j in range(n_features):
            epsilon = epsilon - beta[j]*X[:,j]
            
        #更新 beta
        for j in range(n_features):
            gradient = -np.mean(epsilon*X[:,j])
            beta[j] = beta[j] - alpha*gradient

    return beta

In [2]:
# Load the Drive helper and mount
from google.colab import drive

# This will prompt for authorization.
drive.mount('/content/drive')

# !mkdir -p ~/.kaggle/
# !ln -s '/content/drive/My Drive/kaggle_play/kaggle.json' ~/.kaggle/kaggle.json
# import kaggle
# import tensorflow as tf
import pandas as pd
import numpy as np
import cv2
import os
from copy import deepcopy
%matplotlib inline

from sklearn.linear_model import LinearRegression

data_dir = '/content/drive/My Drive/kaggle_play/kaikeba/lesson_1'

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive


In [19]:
# 确认实现的LinearRegression函数得到的结果与sklearn中的LinearRegression的结果相同
import pandas as pd
from sklearn.metrics import mean_squared_error
data_dir = '/content/drive/My Drive/kaggle_play/kaikeba/lesson_1'
data = pd.read_csv('{}/height_train.csv'.format(data_dir))
# data = data.dropna(how='any')
# data['constant'] = 1
# model = LinearRegression(data.loc[:,['father_height','mother_height','boy_dummy','constant']].values,data.child_height.values,0.1,100000)
model = LinearRegression()
# data.to_csv('/content/drive/My Drive/kaggle_play/kaikeba/lesson_3/123123.csv')
model.fit(X = data[['father_height','mother_height','boy_dummy']],y = data.child_height)
print(model.coef_)
print(model.intercept_)

y_pred = model.predict(X = data[['father_height','mother_height','boy_dummy']])
y_true = data.child_height

print('mse is {}'.format(mean_squared_error(y_true, y_pred)))

[0.23959427 0.25013358 0.10030806]
0.8274299645517071
mse is 0.00012034285005390992


In [0]:
import numpy as np

作业： 实现线性回归的代码，发布到各人Github

选作：
1. 收敛条件的判断
2. 学习率的选择
3. 类的形式

In [38]:
import numpy as np

class LinearRegression_zjz:
  def __init__(self, debug = False):
    self.n_rows = None
    self.debug = debug
    self.fit_flag = False
  
  def fit(self, X, y, alpha = 1e-3, d = 1e-3, max_loop = 100000):
    # print('111111111111111111111111111111111111111111111111111111111111')
    self.n_rows = X.shape[0]
    self.n_features = X.shape[1]

    # 将y转换为二阶矩阵，否则会被broadcasting
    y = y.values.reshape((-1,1))

    if self.debug:
      print('n_rows ===> {}'.format(self.n_rows))
      print('n_feature ===> {}'.format(self.n_features))

    # 添加一列特征， 值为1
    X_ = np.pad(X.values,((0,0),(0,1)),'constant', constant_values=(0,1)) # n * m 
    X_.astype(float)
    beta = np.zeros(shape=(self.n_features + 1, 1)) # m , 1

    for i in range(max_loop):
      epsilon = y - np.matmul(X_, beta) # n, 1
      g = - 2 * np.matmul(X_.T, epsilon) / self.n_rows
      
      if np.linalg.norm(g) * alpha < d:
        break
        
      beta -= alpha * g
      if self.debug:
        print('beta === > {}'.format(beta))
        print('epsilon === > {}'.format(epsilon))

    self.beta = beta
    self.fit_flag = True
    
    print('beta is {}'.format(beta))
       
  @property
  def intercept_(self):
    assert self.fit_flag, "need fit model first"
    return self.beta[-1]

  @property
  def coef_(self):
    assert self.fit_flag, "need fit model first"
    return self.beta[:-1]
  
  def predict(self, X):
    assert self.fit_flag, "need fit model first"
    X_ = np.pad(X.copy(),((0,0),(0,1)),'constant', constant_values=(0,1))
    return np.matmul(X_, self.beta)

import pandas as pd
data_dir = '/content/drive/My Drive/kaggle_play/kaikeba/lesson_1'
data = pd.read_csv('{}/height_train.csv'.format(data_dir))
model2 = LinearRegression_zjz(debug=False)
model2.fit(X = data[['father_height','mother_height','boy_dummy']],y = data.child_height, alpha = 1e-5, max_loop=1000000, d = 1e-8)
# print(model.coef_)
# print(model.intercept_)

y_pred = model2.predict(X = data[['father_height','mother_height','boy_dummy']])
y_true = data.child_height

print('mse is {}'.format(mean_squared_error(y_true, y_pred)))


beta is [[0.42839262]
 [0.40312608]
 [0.10203117]
 [0.25021702]]
mse is 0.0002626988598804039


In [0]:
import numpy as np
array = np.array([[1, 1],[2,2]])
ndarray=np.pad(array,((0,0),(0,1)),'constant', constant_values=(0,1)) 

print("array",array)
print("ndarray=",ndarray)

array [[1 1]
 [2 2]]
ndarray= [[1 1 1]
 [2 2 1]]


In [68]:
import numpy as np

class LinearRegression_3:
  def __init__(self, debug = False):
    self.n_rows = None
    self.debug = debug
    self.fit_flag = False
  
  def fit(self, X,y,alpha,n_rounds):
    n_features = X.shape[1]
    beta = np.array([0.0]*n_features)
    for i in range(n_rounds):

        #计算 epsilon
        epsilon = y
        for j in range(n_features):
            epsilon = epsilon - beta[j]*X[:,j]

        #更新 beta
        for j in range(n_features):
            gradient = -np.mean(epsilon*X[:,j])
            beta[j] = beta[j] - alpha*gradient
    self.beta = beta
    self.fit_flag = True

#       return beta
       
  @property
  def intercept_(self):
    assert self.fit_flag, "need fit model first"
    return self.beta[-1]

  @property
  def coef_(self):
    assert self.fit_flag, "need fit model first"
    return self.beta[:-1]
  
  def predict(self, X):
    assert self.fit_flag, "need fit model first"
#     X_ = np.pad(X.copy(),((0,0),(0,1)),'constant', constant_values=(0,1))
    # X_ = X.copy()
    return np.matmul(X, self.beta)

import pandas as pd
data_dir = '/content/drive/My Drive/kaggle_play/kaikeba/lesson_1'
data = pd.read_csv('{}/height_train.csv'.format(data_dir))
data['const'] = 1.0
model2 = LinearRegression_3(debug=False)
model2.fit(X = data[['father_height','mother_height','boy_dummy', 'const']].values,y = data.child_height.values, alpha = 1e-2, n_rounds= 24000)
print(model2.coef_)
print(model2.intercept_)



y_pred = model2.predict(X = data[['father_height','mother_height','boy_dummy', 'const']].values)
y_true = data.child_height

print('mse is {}'.format(mean_squared_error(y_true, y_pred)))

[0.40769183 0.39781116 0.10022758]
0.2957043850857928
mse is 0.00023973505849415568


In [59]:
import numpy as np

class LinearRegression_3:
  def __init__(self, debug = False):
    self.n_rows = None
    self.n_features = None
    self.debug = debug
    self.fit_flag = False
  
  def fit(self, X,y,alpha,n_rounds, phi = None, decay = None):
    self.n_features = X.shape[1]
    self.n_rows = X.shape[0]
    X = np.pad(X.copy(),((0,0),(0,1)),'constant', constant_values=(0,1))
    beta = np.array([0.0]*X.shape[1])
    for i in range(n_rounds):
        epsilon = y - np.matmul(X, beta)
        gradient = - np.matmul(X.T, epsilon) / X.shape[0]
        if decay:
          for d in decay:
            if i == d:
              alpha *= 0.1
        beta = beta - alpha * gradient
        if phi:
          if np.linalg.norm(epsilon) < 1e-4:
            break
    self.beta = beta
    self.fit_flag = True
       
  @property
  def intercept_(self):
    assert self.fit_flag, "need fit model first"
    return self.beta[-1]

  @property
  def coef_(self):
    assert self.fit_flag, "need fit model first"
    return self.beta[:-1]
  
  def predict(self, X):
    assert self.fit_flag, "need fit model first"
    X = np.pad(X.copy(),((0,0),(0,1)),'constant', constant_values=(0,1))
    return np.matmul(X, self.beta)

import pandas as pd
data_dir = '/content/drive/My Drive/kaggle_play/kaikeba/lesson_1'
data = pd.read_csv('{}/height_train.csv'.format(data_dir))
# data['const'] = 1
model2 = LinearRegression_3(debug=False)
model2.fit(X = data[['father_height','mother_height','boy_dummy']].values,y = data.child_height.values, alpha = 1e-3, n_rounds= 10000)
print(model2.coef_)
print(model2.intercept_)



y_pred = model2.predict(X = data[['father_height','mother_height','boy_dummy']].values)
y_true = data.child_height

print('mse is {}'.format(mean_squared_error(y_true, y_pred)))


# [0.23959427 0.25013358 0.10030806]
# 0.8274299645517071
# mse is 0.00012034285005390992

[0.42843961 0.40304645 0.1028789 ]
0.2498180485405663
mse is 0.0002638174770896327
